### signup user1
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456",
    "workspace": "edg"
}

### signup user2
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "kk",
    "email": "kk@acme.org",
    "password": "123456",
    "workspace": "edg"
}

### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}

### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "edg_2024_championship",
    "members": [1, 2],
    "public": false
}


### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get users list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}
